### ISSUE TITLE
[PROPOSAL] PIMO Play save masking.yml on ctrl+s

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#148]
This is a proposal to intercept the `CTRL+S` user's action and change the default browser behavior to download the current masking cell as a `masking.yml` file.

the trick is to call  JS function that create a hidden link `<a href=...>` somewhere in the page and click it and then remove this link.

**Comment by youen** [comment]
pock @adrienaury

**Comment by adrienaury** [comment]
Optionnal : if the user already used the CTRL+S command previously, then reuse the filename (eg: the user save the file as "masking-custom.yml", the next saving should propose "masking-custom.yml" as filename).
