### ISSUE TITLE
[PROPOSAL] HTTP API service

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#15]
# HTTP Service 

This is proposal  to expose PIMO's pipeline as a HTTP service.

## Stateless vs  Statefull

PIMO's pipeline could be statefull (if it's using sequence mask or cache) or stateless. For this proposal PIMO HTTP API is stateless and each HTTP request simulate a PIMO's run. A statefull implementation will be propose in an other issue.

## HTTP server

The command `pimo --http` start the http server on port `8000` . Port is configurable with the `--port` option.

## HTTP API

The root path is `/api/v1/`

### GET

HTTP `GET` method simulate the `--empty-input` option

### POST

HTTP `POST` method send the input as a body to the server

**Comment by adrienaury** [comment]
This has been developped in v1.21.0

> Added new flag --serve to start a HTTP server that apply masking to JSON body of requests
