### ISSUE TITLE
[PROPOSAL] PIMO PLAY add a quick way to clear inputs

### ISSUE THREAD

**Issue by pbq** [CGI-FR/PIMO#161]
This is a proposal to add a clear inputs feature.
You can click on each bins to clear each input or on the general bin to clear all.
![image](https://user-images.githubusercontent.com/4497414/184312085-8321cf50-c243-43e3-9905-20976418d6d0.png)
or
you can click on the pimo play logo/link to go to a fresh new playground page.
![image](https://user-images.githubusercontent.com/4497414/184312327-10672267-ceca-4676-abd4-3f8214d9aced.png)

**Comment by adrienaury** [comment]
Currently, clicking the PIMO Play logo will reset fields with a simple default value. 
I think it's close enough, what do you think ?

**Comment by pbq** [comment]
it's perfect. 
thank you Adrien.
